name: Common workflow
run-name: 1.0.0

on:
  workflow_call:
#    inputs:
#      config-path:
#        required: true
#        type: string
#    secrets:
#      token:
#        required: true

jobs:
  BuildJob:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      apiVersion: ${{ steps.api_version.outputs.apiVersion }}
    steps:
#    - uses: actions/labeler@v4
#      with:
#        repo-token: ${{ secrets.token }}
#        configuration-path: ${{ inputs.config-path }}
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - name: Get version from pom
      run:  |
        pomVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Export api version
      id: api_version
#      run: echo "apiVersion=$pomVersion" >> "$GITHUB_OUTPUT"
      run: echo "apiVersion=1.0.0" >> "$GITHUB_OUTPUT"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "The workflow is now ready to test your code on the runner."
    - run: echo "The version is $pomVersion" 
    
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "This job's status is ${{ job.status }}."
    - name: Save apiVersion to file
        uses: actions/upload-artifact@v4
        with:
          name: api_version_from_file
          path: api-version.txt

  DeployDev:
    name: Deploy ${{ needs.BuildJob.outputs.apiVersion }} to DEV
    runs-on: ubuntu-latest
    needs: BuildJob
    environment:
      name: DEV
      url: 'http://dev-api.copeland.com'
    steps:
      - env:
          API_VERSION: ${{ needs.BuildJob.outputs.apiVersion }}
        run: echo "$API_VERSION ..."
      - name: Deploy to DEV	  
        run: echo "Deploying to DEV environment version $API_VERSION ..."
      - run: echo "This job's status is ${{ job.status }}."
      - name: Retrieve apiVersion from file
        uses: actions/download-artifact@v4
        with:
          name: api_version_from_file
      - shell: bash
        run: |
          apiVersionFromFile=`cat api-version.txt`
      - run: echo "value from file= $apiVersionFromFile"

  DeploySit:
    name: Deploy ${{ needs.BuildJob.outputs.apiVersion }} to SIT
    runs-on: ubuntu-latest
    needs: [DeployDev]
    environment:
      name: SIT
      url: 'http://sit-api.copeland.com'
    steps:
      - env:
          API_VERSION: ${{ needs.BuildJob.outputs.apiVersion }}
        run: echo "$API_VERSION ..."    
      - name: Deploy to SIT
        run: echo Deploying to SIT environment...
      - run: echo "This job's status is ${{ job.status }}."

